// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cube
double cube(double x);
RcppExport SEXP _mypackage_10_31_25_3_cube(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cube(x));
    return rcpp_result_gen;
END_RCPP
}
// median_cpp_new
double median_cpp_new(NumericVector x);
RcppExport SEXP _mypackage_10_31_25_3_median_cpp_new(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(median_cpp_new(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mypackage_10_31_25_3_cube", (DL_FUNC) &_mypackage_10_31_25_3_cube, 1},
    {"_mypackage_10_31_25_3_median_cpp_new", (DL_FUNC) &_mypackage_10_31_25_3_median_cpp_new, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mypackage_10_31_25_3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
